import type { ArchitecturalHouse, PropertyDefinition } from "./architecturalTypes";
import { LOT_1A_FOOTPRINT } from './site/lot1aFootprint';
import { LOT_1A_SITE_LAYOUT, mapSiteLayoutToSurfaces } from './site/lot1aSurfaces';
import {
  doorDetailed,
  firstFloorTransom,
  frontDormerWindow,
  frontFirstTallWindow,
  frontGroundTallWindow,
  frontPortalDoor,
  frontSmallWindow,
  leftFacadeShortWindow,
  leftFacadeTallLowerWindow,
  leftFacadeTallUpperWindow,
  plainWindow,
} from './styles/openingStylePresets';

const FOOTPRINTS = {
  basement: {
    id: 'basement-footprint',
    derivedFrom: null,
    outer: [
      { x: 4.8, z: 15 },
      { x: 4.1, z: 15 },
      { x: -3.5, z: 15 },
      { x: -3.5, z: 12 },
      { x: -3.5, z: 8.45 },
      { x: -4.1, z: 8.45 },
      { x: -4.1, z: 4 },
      { x: -4.8, z: 4 },
      { x: -4.8, z: 0 },
      { x: 4.8, z: 0 },
    ],
    edges: [
      { id: 'rear-right-return', side: 'rear', edgeIndex: 0, from: { x: 4.8, z: 15 }, to: { x: 4.1, z: 15 } },
      { id: 'rear-main', side: 'rear', edgeIndex: 1, from: { x: 4.1, z: 15 }, to: { x: -3.5, z: 15 } },
      { id: 'left-rear', side: 'left', edgeIndex: 2, from: { x: -3.5, z: 15 }, to: { x: -3.5, z: 12 } },
      { id: 'left-upper-middle', side: 'left', edgeIndex: 3, from: { x: -3.5, z: 12 }, to: { x: -3.5, z: 8.45 } },
      { id: 'left-step', side: 'left', edgeIndex: 4, from: { x: -3.5, z: 8.45 }, to: { x: -4.1, z: 8.45 } },
      { id: 'left-middle', side: 'left', edgeIndex: 5, from: { x: -4.1, z: 8.45 }, to: { x: -4.1, z: 4 } },
      { id: 'left-front-step', side: 'left', edgeIndex: 6, from: { x: -4.1, z: 4 }, to: { x: -4.8, z: 4 } },
      { id: 'left-front', side: 'left', edgeIndex: 7, from: { x: -4.8, z: 4 }, to: { x: -4.8, z: 0 } },
      { id: 'front-main', side: 'front', edgeIndex: 8, from: { x: -4.8, z: 0 }, to: { x: 4.8, z: 0 } },
      { id: 'right-main', side: 'right', edgeIndex: 9, from: { x: 4.8, z: 0 }, to: { x: 4.8, z: 15 } },
    ],
    semanticZones: [
      { id: 'front-volume', minX: -4.8, maxX: 4.8, minZ: 0, maxZ: 4 },
      { id: 'middle-volume', minX: -4.1, maxX: 4.8, minZ: 4, maxZ: 8.45 },
      { id: 'rear-volume', minX: -3.5, maxX: 4.8, minZ: 8.45, maxZ: 15 },
    ],
  },
  ground: {
    id: 'ground-footprint',
    derivedFrom: 'basement',
    outer: [
      { x: 4.8, z: 15 },
      { x: 4.1, z: 15 },
      { x: -3.5, z: 15 },
      { x: -3.5, z: 12 },
      { x: -3.5, z: 8.45 },
      { x: -4.1, z: 8.45 },
      { x: -4.1, z: 4 },
      { x: -4.8, z: 4 },
      { x: -4.8, z: 0 },
      { x: 4.8, z: 0 },
    ],
    edges: [],
    semanticZones: [],
  },
  first: {
    id: 'first-footprint',
    derivedFrom: 'ground',
    outer: [
      { x: -3.5, z: 12 },
      { x: -3.5, z: 8.45 },
      { x: -4.1, z: 8.45 },
      { x: -4.1, z: 4 },
      { x: -4.8, z: 4 },
      { x: -4.8, z: 0 },
      { x: 4.8, z: 0 },
      { x: 4.8, z: 4 },
      { x: 4.8, z: 8.45 },
      { x: 4.8, z: 12 },
    ],
    differences: [
      { id: 'rear-cutout', type: 'removeRearSection', minX: -3.5, maxX: 4.8, minZ: 12, maxZ: 15 },
    ],
    edges: [
      { id: 'left-rear', side: 'left', edgeIndex: 0 },
      { id: 'left-upper-middle', side: 'left', edgeIndex: 1 },
      { id: 'left-middle', side: 'left', edgeIndex: 2 },
      { id: 'left-front-step', side: 'left', edgeIndex: 3 },
      { id: 'left-front', side: 'left', edgeIndex: 4 },
      { id: 'front-main', side: 'front', edgeIndex: 5 },
      { id: 'right-front', side: 'right', edgeIndex: 6 },
      { id: 'right-middle', side: 'right', edgeIndex: 7 },
      { id: 'right-upper-middle', side: 'right', edgeIndex: 8 },
      { id: 'rear-main', side: 'rear', edgeIndex: 9 },
    ],
  },
};

type FootprintLevelId = keyof typeof FOOTPRINTS;

const getFootprintForLevel = (levelId: FootprintLevelId) => FOOTPRINTS[levelId];

const getEdgeIndex = (levelId: FootprintLevelId, edgeId: string): number => {
  const footprint = getFootprintForLevel(levelId);
  const edge = footprint.edges.find((item) => item.id === edgeId);

  if (edge) return edge.edgeIndex;
  if (footprint.derivedFrom) return getEdgeIndex(footprint.derivedFrom, edgeId);

  throw new Error(`Unknown edge "${edgeId}" for level "${levelId}"`);
};

// The ground-floor side-elevation drawing calls out a 215cm-high door, while the
// first-floor plan dimensions the right-side window at 80cm wide with its sill at
// +410cm above grade. Keep both openings on the long, flat right facade run and
// aligned to the same approximate z=5.50m centreline from the front edge.

export const propertyDefinition: PropertyDefinition = {
  id: 'lot-1a',
  site: {
    elevation: -0.001,
    color: '#6DAA2C',
    footprint: LOT_1A_FOOTPRINT,
    surfaces: mapSiteLayoutToSurfaces(LOT_1A_SITE_LAYOUT, FOOTPRINTS.ground.outer),
    boundaries: {
      fences: [],
      hedges: [],
      gates: [],
    },
    objects: [
      {
        id: 'carport-main',
        type: 'carport',
        attachedTo: {
          side: 'right',
        },
        footprint: {
          outer: [
            { x: 4.8, z: 0.0 },
            { x: 8.55, z: 0.0 },
            { x: 8.55, z: 15.0 },
            { x: 4.8, z: 15.0 },
          ],
        },
        heightOffsetFromRoof: -0.5,
        thickness: 0.2,
        columns: {
          spacing: 3.0,
          size: 0.15,
          insetFromEdge: 0.1,
          sides: {
            front: false,
            rear: false,
            houseSide: false,
            outerSide: true,
          },
        },
        material: {
          roof: 'flat_roof_dark',
          columns: 'wood_oak_light',
          underside: '/textures/fence/wood.jpg',
        },
      },
    ],
  },
  house: {
    wallThickness: 0.3,
    levels: [
    {
      id: 'basement',
      name: 'Basement',
      elevation: -3.1,
      height: 2.8,
      slab: { thickness: 0.3, inset: 0 },
      footprint: { ...FOOTPRINTS.basement },
    },
    {
      id: 'ground',
      name: 'Ground',
      elevation: 0,
      height: 2.8,
      slab: { thickness: 0.3, inset: 0 },
      footprint: { ...FOOTPRINTS.ground },
    },
    {
      id: 'first',
      name: 'First',
      elevation: 3.05,
      height: 2.8,
      slab: { thickness: 0.25, inset: 0 },
      footprint: { ...FOOTPRINTS.first },
    },
  ],
  rooms: [
    {
      id: 'room-ground-office',
      name: 'Office',
      levelId: 'ground',
      polygon: [
        { x: -4.8, z: 0.0 },
        { x: 0.2, z: 0.0 },
        { x: 0.2, z: 4.0 },
        { x: -4.8, z: 4.0 },
      ],
      edges: [
        { type: 'exterior' },
        { type: 'wall' },
        { type: 'wall' },
        { type: 'exterior' },
      ],
    },

    {
      id: 'room-ground-hall',
      name: 'Hall',
      levelId: 'ground',
      polygon: [
        { x: 0.2, z: 0.0 },
        { x: 2.3, z: 0.0 },
        { x: 2.3, z: 4.0 },
        { x: 0.2, z: 4.0 },
      ],
      edges: [
        { type: 'exterior' },
        { type: 'wall' },
        { type: 'wall' },
        { type: 'wall' },
      ],
    },

    {
      id: 'room-ground-wc',
      name: 'WC',
      levelId: 'ground',
      polygon: [
        { x: 2.3, z: 0.0 },
        { x: 4.8, z: 0.0 },
        { x: 4.8, z: 1.8 },
        { x: 2.3, z: 1.8 },
      ],
      edges: [
        { type: 'exterior' },
        { type: 'exterior' },
        { type: 'wall' },
        { type: 'wall' },
      ],
    },

    {
      id: 'room-ground-lounge',
      name: 'Lounge',
      levelId: 'ground',
      polygon: [
        { x: -4.1, z: 4.0 },
        { x: 1.0, z: 4.0 },
        { x: 1.0, z: 8.45 },
        { x: -3.5, z: 8.45 },
        { x: -4.1, z: 8.45 },
      ],
      edges: [
        { type: 'wall' },
        { type: 'wall' },
        { type: 'open' },
        { type: 'exterior' },
        { type: 'exterior' },
      ],
    },

    {
      id: 'room-ground-stairs-core',
      name: 'Stairs Core',
      levelId: 'ground',
      polygon: [
        { x: 1.0, z: 4.0 },
        { x: 2.7, z: 4.0 },
        { x: 2.7, z: 6.2 },
        { x: 1.0, z: 6.2 },
      ],
      edges: [
        { type: 'wall' },
        { type: 'wall' },
        { type: 'wall' },
        { type: 'wall' },
      ],
    },
    {
      id: 'room-ground-storage-entry',
      name: 'Storage',
      levelId: 'ground',
      polygon: [
        { x: 2.3, z: 1.8 },
        { x: 4.8, z: 1.8 },
        { x: 4.8, z: 8.45 },
        { x: 1.0, z: 8.45 },
        { x: 1.0, z: 6.2 },
        { x: 2.7, z: 6.2 },
        { x: 2.7, z: 4.0 },
        { x: 2.3, z: 4.0 },
      ],
      edges: [
        { type: 'wall' },
        { type: 'exterior' },
        { type: 'exterior' },
        { type: 'wall' },
        { type: 'wall' },
        { type: 'wall' },
        { type: 'wall' },
        { type: 'wall' },
      ],
    },
    {
      id: 'room-ground-kitchen',
      name: 'Kitchen',
      levelId: 'ground',
      polygon: [
        { x: -3.5, z: 8.45 },
        { x: 4.8, z: 8.45 },
        { x: 4.8, z: 11.6 },
        { x: -3.5, z: 11.6 },
      ],
      edges: [
        { type: 'open' },
        { type: 'exterior' },
        { type: 'wall' },
        { type: 'exterior' },
      ],
    },

    {
      id: 'room-ground-dining',
      name: 'Dining',
      levelId: 'ground',
      polygon: [
        { x: -3.5, z: 11.6 },
        { x: 4.8, z: 11.6 },
        { x: 4.8, z: 15.0 },
        { x: -3.5, z: 15.0 },
      ],
      edges: [
        { type: 'wall' },
        { type: 'exterior' },
        { type: 'exterior' },
        { type: 'exterior' },
      ],
    },
  ],


  materials: {
    walls: {
      texture: '/textures/brick1.jpg',
      scale: 1,
      interiorColor: '#f6f1e7',
    },
    windows: {
      frameColor: '#383e42',
      glassColor: '#a8d0ff',
      glassOpacity: 0.35,
    },
    roof: {
      color: '#333333',
    },
  },

  roofs: [
    {
      id: "ground-flat",
      type: "flat",
      baseLevelId: "ground",
      subtractAboveLevelId: "first",
      thickness: 0.2,
    },
    {
      id: "main-roof",
      type: "multi-plane",
      baseLevelId: "first",
      eaveHeight: 2.8,
      thickness: 0.2,
      overhang: 0,
      ridgeSegments: [
        {
          id: "main",
          start: { x: 0.6, z: 8.7 },
          end: { x: 0.6, z: 4.31 },
          height: 6.45,
        },
      ],
      faces: [
        {
          id: "left-start",
          kind: "ridgeSideSegment",
          ridgeId: "main",
          side: "left",
          capEnd: "start",
          ridgeT0: 0.0,
          ridgeT1: 0.5,
          region: {
            type: "compound",
            items: [
              { type: "ridgePerpCut", ridgeId: "main", t: 0.0, keep: "ahead" },
              { type: "ridgePerpCut", ridgeId: "main", t: 0.5, keep: "behind" },
            ],
          },
        },
        {
          id: "left-end",
          kind: "ridgeSideSegment",
          ridgeId: "main",
          side: "left",
          capEnd: "end",
          ridgeT0: 0.5,
          ridgeT1: 1.0,
          region: {
            type: "compound",
            items: [
              { type: "ridgePerpCut", ridgeId: "main", t: 0.5, keep: "ahead" },
              { type: "ridgePerpCut", ridgeId: "main", t: 1.0, keep: "behind" },
            ],
          },
        },
        {
          id: "right-start",
          kind: "ridgeSideSegment",
          ridgeId: "main",
          side: "right",
          capEnd: "start",
          ridgeT0: 0.0,
          ridgeT1: 0.5,
          region: {
            type: "compound",
            items: [
              { type: "ridgePerpCut", ridgeId: "main", t: 0.0, keep: "ahead" },
              { type: "ridgePerpCut", ridgeId: "main", t: 0.5, keep: "behind" },
            ],
          },
        },
        {
          id: "right-end",
          kind: "ridgeSideSegment",
          ridgeId: "main",
          side: "right",
          capEnd: "end",
          ridgeT0: 0.5,
          ridgeT1: 1.0,
          region: {
            type: "compound",
            items: [
              { type: "ridgePerpCut", ridgeId: "main", t: 0.5, keep: "ahead" },
              { type: "ridgePerpCut", ridgeId: "main", t: 1.0, keep: "behind" },
            ],
          },
        },
        {
          id: "hip-front",
          kind: "hipCap",
          region: { type: "ridgeCapTriangle", ridgeId: "main", end: "start" },
        },
        {
          id: "hip-end",
          kind: "hipCap",
          region: { type: "ridgeCapTriangle", ridgeId: "main", end: "end" },
        },
      ],
    },
  ],

  openings: [
    {
      id: 'FRONT_G_W1',
      kind: 'window',
      levelId: 'ground',
      edge: { levelId: 'ground', ring: 'outer', edgeId: 'front-main', edgeIndex: getEdgeIndex('ground', 'front-main') },
      offset: 1.7,
      width: 1.1,
      sillHeight: 0.7,
      height: 1.6,
      style: frontGroundTallWindow,
    },
    {
      id: 'FRONT_G_W2',
      kind: 'window',
      levelId: 'ground',
      edge: { levelId: 'ground', ring: 'outer', edgeId: 'front-main', edgeIndex: getEdgeIndex('ground', 'front-main') },
      offset: 3.5,
      width: 1.1,
      sillHeight: 0.7,
      height: 1.6,
      style: frontGroundTallWindow,
    },
    {
      id: 'FRONT_G_DOOR',
      kind: 'door',
      levelId: 'ground',
      edge: { levelId: 'ground', ring: 'outer', edgeId: 'front-main', edgeIndex: getEdgeIndex('ground', 'front-main') },
      offset: 5.5,
      width: 1,
      sillHeight: 0,
      height: 2.5,
      style: frontPortalDoor,
    },
    {
      id: 'FRONT_G_W3',
      kind: 'window',
      levelId: 'ground',
      edge: { levelId: 'ground', ring: 'outer', edgeId: 'front-main', edgeIndex: getEdgeIndex('ground', 'front-main') },
      offset: 7.5,
      width: 0.7,
      sillHeight: 1.65,
      height: 0.5,
      style: frontSmallWindow,
    },
    {
      id: 'FRONT_F_W1',
      kind: 'window',
      levelId: 'first',
      edge: { levelId: 'first', ring: 'outer', edgeId: 'front-main', edgeIndex: getEdgeIndex('first', 'front-main') },
      offset: 1.7,
      width: 0.9,
      sillHeight: 0.35,
      height: 1.6,
      style: frontFirstTallWindow,
    },
    {
      id: 'FRONT_F_W2',
      kind: 'window',
      levelId: 'first',
      edge: { levelId: 'first', ring: 'outer', edgeId: 'front-main', edgeIndex: getEdgeIndex('first', 'front-main') },
      offset: 3.5,
      width: 0.9,
      sillHeight: 0.35,
      height: 1.6,
      style: frontFirstTallWindow,
    },
    {
      id: 'FRONT_F_W3',
      kind: 'window',
      levelId: 'first',
      edge: { levelId: 'first', ring: 'outer', edgeId: 'front-main', edgeIndex: getEdgeIndex('first', 'front-main') },
      offset: 5.5,
      width: 0.9,
      sillHeight: 1.8,
      height: 1,
      style: frontDormerWindow,
    },
    {
      id: 'FRONT_F_W4',
      kind: 'window',
      levelId: 'first',
      edge: { levelId: 'first', ring: 'outer', edgeId: 'front-main', edgeIndex: getEdgeIndex('first', 'front-main') },
      offset: 7.5,
      width: 0.7,
      sillHeight: 1.3,
      height: 0.9,
      style: frontSmallWindow,
    },
    {
      id: 'REAR_G_GLAZED',
      kind: 'window',
      levelId: 'ground',
      edge: { levelId: 'ground', ring: 'outer', edgeId: 'rear-main', edgeIndex: getEdgeIndex('ground', 'rear-main') },
      offset: 1,
      width: 5.6,
      sillHeight: 0,
      height: 2.45,
      style: {
        variant: 'plain',
        grid: { cols: 3, rows: 1 },
        hasSill: true,
        sillDepth: 0.12,
        sillThickness: 0.03,
        hasLintel: true,
      },
    },
    {
      id: 'REAR_F_W_LEFT',
      kind: 'window',
      levelId: 'first',
      edge: { levelId: 'first', ring: 'outer', edgeId: 'rear-main', edgeIndex: getEdgeIndex('first', 'rear-main'), fromEnd: true },
      offset: 2.05,
      width: 1.1,
      sillHeight: 0.35,
      height: 1.6,
      style: firstFloorTransom,
    },
    {
      id: 'REAR_F_W_RIGHT',
      kind: 'window',
      levelId: 'first',
      edge: { levelId: 'first', ring: 'outer', edgeId: 'rear-main', edgeIndex: getEdgeIndex('first', 'rear-main'), fromEnd: true },
      offset: 5.15,
      width: 1.1,
      sillHeight: 0.35,
      height: 1.6,
      style: firstFloorTransom,
    },
    {
      id: 'RIGHT_G_DOOR',
      kind: 'door',
      levelId: 'ground',
      edge: { levelId: 'ground', ring: 'outer', edgeId: 'right-main', edgeIndex: getEdgeIndex('ground', 'right-main') },
      offset: 5.05,
      width: 0.9,
      sillHeight: 0,
      height: 2.15,
      style: doorDetailed,
    },
    {
      id: 'RIGHT_B_BASEMENT_DOOR',
      kind: 'door',
      levelId: 'basement',
      edge: { levelId: 'basement', ring: 'outer', edgeId: 'right-main', edgeIndex: getEdgeIndex('basement', 'right-main') },
      offset: 8.55,
      width: 0.95,
      sillHeight: 0,
      height: 2.15,
      style: doorDetailed,
    },
    {
      id: 'RIGHT_F_WINDOW',
      kind: 'window',
      levelId: 'first',
      edge: { levelId: 'first', ring: 'outer', edgeId: 'right-middle', edgeIndex: getEdgeIndex('first', 'right-middle') },
      offset: 1.1,
      width: 0.8,
      sillHeight: 1.05,
      height: 0.9,
      style: plainWindow,
    },
    {
      id: 'LEFT_STACK_LOW_G',
      kind: 'window',
      levelId: 'ground',
      edge: { levelId: 'ground', ring: 'outer', edgeId: 'left-rear', edgeIndex: getEdgeIndex('ground', 'left-rear'), fromEnd: false },
      offset: 1.3,
      width: 0.7,
      sillHeight: 0,
      height: 2.15,
      style: leftFacadeShortWindow,
    },
    {
      id: 'LEFT_STACK_MID_G',
      kind: 'window',
      levelId: 'ground',
      edge: { levelId: 'ground', ring: 'outer', edgeId: 'left-middle', edgeIndex: getEdgeIndex('ground', 'left-middle'), fromEnd: true },
      offset: 1,
      width: 0.8,
      sillHeight: 0,
      height: 2.8,
      style: leftFacadeTallLowerWindow,
    },
    {
      id: 'LEFT_STACK_MID_F',
      kind: 'window',
      levelId: 'first',
      edge: { levelId: 'first', ring: 'outer', edgeId: 'left-middle', edgeIndex: getEdgeIndex('first', 'left-middle'), fromEnd: true },
      offset: 1,
      width: 0.8,
      sillHeight: 0,
      height: 1.95,
      style: leftFacadeTallUpperWindow,
    },
    {
      id: 'LEFT_STACK_MID_B_G',
      kind: 'window',
      levelId: 'ground',
      edge: { levelId: 'ground', ring: 'outer', edgeId: 'left-middle', edgeIndex: getEdgeIndex('ground', 'left-middle'), fromEnd: true },
      offset: 2.65,
      width: 0.8,
      sillHeight: 0,
      height: 2.8,
      style: leftFacadeTallLowerWindow,
    },
    {
      id: 'LEFT_STACK_MID_B_F',
      kind: 'window',
      levelId: 'first',
      edge: { levelId: 'first', ring: 'outer', edgeId: 'left-middle', edgeIndex: getEdgeIndex('first', 'left-middle'), fromEnd: true },
      offset: 2.65,
      width: 0.8,
      sillHeight: 0,
      height: 1.95,
      style: leftFacadeTallUpperWindow,
    },
    {
      id: 'LEFT_STACK_HIGH_G',
      kind: 'window',
      levelId: 'ground',
      edge: { levelId: 'ground', ring: 'outer', edgeId: 'left-upper-middle', edgeIndex: getEdgeIndex('ground', 'left-upper-middle'), fromEnd: true },
      offset: 1.3,
      width: 0.8,
      sillHeight: 0,
      height: 2.8,
      style: leftFacadeTallLowerWindow,
    },
    {
      id: 'LEFT_STACK_HIGH_F',
      kind: 'window',
      levelId: 'first',
      edge: { levelId: 'first', ring: 'outer', edgeId: 'left-rear', edgeIndex: getEdgeIndex('first', 'left-rear'), fromEnd: true },
      offset: 1.3,
      width: 0.8,
      sillHeight: 0,
      height: 1.95,
      style: leftFacadeTallUpperWindow,
    },
  ],

  exteriorAccesses: [
    {
      id: 'BASEMENT_RIGHT_REAR_ACCESS',
      levelId: 'basement',
      edge: { levelId: 'basement', ring: 'outer', edgeId: 'right-main', edgeIndex: getEdgeIndex('basement', 'right-main') },
      offset: 8.25,
      wellWidth: 1.8,
      landingLength: 1.3,
      stairRun: 5.45,
      stairRise: 3.1,
      stepCount: 17,
      floorThickness: 0.18,
      wallThickness: 0.2,
      wallHeight: 3.1,
      guardWallHeight: 1,
    },
  ],
  },
};

export const architecturalHouse: ArchitecturalHouse = propertyDefinition.house;
